$primary_paletteKeyColor = 528251
$secondary_paletteKeyColor = 6a7c67
$tertiary_paletteKeyColor = 527e84
$neutral_paletteKeyColor = 747871
$neutral_variant_paletteKeyColor = 72796f
$background = 10140f
$onBackground = e0e4db
$surface = 10140f
$surfaceDim = 10140f
$surfaceBright = 363a34
$surfaceContainerLowest = 0b0f0a
$surfaceContainerLow = 181d17
$surfaceContainer = 1c211b
$surfaceContainerHigh = 272b25
$surfaceContainerHighest = 323630
$onSurface = e0e4db
$surfaceVariant = 424940
$onSurfaceVariant = c2c9bd
$inverseSurface = e0e4db
$inverseOnSurface = 2d322c
$outline = 8c9388
$outlineVariant = 424940
$shadow = 000000
$scrim = 000000
$surfaceTint = 9fd49b
$primary = 9fd49b
$onPrimary = 073911
$primaryContainer = 225025
$onPrimaryContainer = bbf0b6
$inversePrimary = 3a693b
$secondary = b9ccb4
$onSecondary = 253424
$secondaryContainer = 3d4d3b
$onSecondaryContainer = d5e8cf
$tertiary = a1ced5
$onTertiary = 00363c
$tertiaryContainer = 6b989e
$onTertiaryContainer = 000000
$error = ffb4ab
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryFixed = bbf0b6
$primaryFixedDim = 9fd49b
$onPrimaryFixed = 002105
$onPrimaryFixedVariant = 225025
$secondaryFixed = d5e8cf
$secondaryFixedDim = b9ccb4
$onSecondaryFixed = 101f10
$onSecondaryFixedVariant = 3b4b39
$tertiaryFixed = bcebf1
$tertiaryFixedDim = a1ced5
$onTertiaryFixed = 001f23
$onTertiaryFixedVariant = 1f4d53
$term0 = 343433
$term1 = 7f9c00
$term2 = 9cdd80
$term3 = c2f58d
$term4 = 84b692
$term5 = c6a844
$term6 = a1d79d
$term7 = d4dbc7
$term8 = a0a595
$term9 = 93b600
$term10 = a3f184
$term11 = ddffba
$term12 = adc8ad
$term13 = cec06b
$term14 = afeaa7
$term15 = ffffff
$rosewater = f2f2e4
$flamingo = e3e4c5
$pink = ffd79d
$mauve = 5bd0df
$red = c5b542
$maroon = c6c177
$peach = c0d694
$yellow = e4f8cf
$green = b1efac
$teal = b3edbe
$sky = a5eabe
$sapphire = 85d8ac
$blue = 6acfa9
$lavender = 89dcc6
$text = e0e4db
$subtext1 = c2c9bd
$subtext0 = 8c9388
$overlay2 = 798076
$overlay1 = 666d63
$overlay0 = 555b53
$surface2 = 444a42
$surface1 = 343932
$surface0 = 222620
$base = 10140f
$mantle = 10140f
$crust = 0f130e
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
