$primary_paletteKeyColor = 777777
$secondary_paletteKeyColor = 777777
$tertiary_paletteKeyColor = 787677
$neutral_paletteKeyColor = 777777
$neutral_variant_paletteKeyColor = 777777
$background = 131313
$onBackground = e2e2e2
$surface = 131313
$surfaceDim = 131313
$surfaceBright = 393939
$surfaceContainerLowest = 0e0e0e
$surfaceContainerLow = 1b1b1b
$surfaceContainer = 1f1f1f
$surfaceContainerHigh = 2a2a2a
$surfaceContainerHighest = 353535
$onSurface = e2e2e2
$surfaceVariant = 474747
$onSurfaceVariant = c6c6c6
$inverseSurface = e2e2e2
$inverseOnSurface = 303030
$outline = 909090
$outlineVariant = 474747
$shadow = 000000
$scrim = 000000
$surfaceTint = c6c6c6
$primary = c6c6c6
$onPrimary = 303030
$primaryContainer = 464646
$onPrimaryContainer = e2e2e2
$inversePrimary = 5e5e5e
$secondary = c7c7c7
$onSecondary = 303030
$secondaryContainer = 474747
$onSecondaryContainer = e2e2e2
$tertiary = c8c5c6
$onTertiary = 303030
$tertiaryContainer = 929091
$onTertiaryContainer = 000000
$error = e4beb9
$onError = 601410
$errorContainer = 891c18
$onErrorContainer = e2e2e2
$primaryFixed = e2e2e2
$primaryFixedDim = c6c6c6
$onPrimaryFixed = 1b1b1b
$onPrimaryFixedVariant = 464646
$secondaryFixed = e2e2e2
$secondaryFixedDim = c7c7c7
$onSecondaryFixed = 1b1b1b
$onSecondaryFixedVariant = 474747
$tertiaryFixed = e4e1e1
$tertiaryFixedDim = c8c5c6
$onTertiaryFixed = 1b1b1c
$onTertiaryFixedVariant = 474747
$term0 = 343434
$term1 = 8888de
$term2 = 88d8e7
$term3 = a6f5df
$term4 = 9cacba
$term5 = 9da9d2
$term6 = adcee0
$term7 = d8d8d8
$term8 = a3a3a3
$term9 = a5a2e1
$term10 = b3e6f1
$term11 = e7f8f3
$term12 = bec1c4
$term13 = b7bedc
$term14 = c8dfeb
$term15 = ffffff
$rosewater = f2f2f2
$flamingo = e1e1e1
$pink = dbdce6
$mauve = afc1e3
$red = a6b2e1
$maroon = b9bdd6
$peach = d8c8e2
$yellow = ecf2f0
$green = d2e2eb
$teal = d7e1ea
$sky = d1dce8
$sapphire = afcae6
$blue = a2bfe4
$lavender = bfcee5
$klink = 688ab1
$klinkSelection = 698ab2
$kvisited = 6480bd
$kvisitedSelection = 6680bd
$knegative = 7281dd
$knegativeSelection = 7480dd
$kneutral = bf9ce4
$kneutralSelection = bf9ce4
$kpositive = 65b1db
$kpositiveSelection = 65b2dd
$text = e2e2e2
$subtext1 = c6c6c6
$subtext0 = 909090
$overlay2 = 7d7d7d
$overlay1 = 6a6a6a
$overlay0 = 595959
$surface2 = 484848
$surface1 = 373737
$surface0 = 252525
$base = 131313
$mantle = 131313
$crust = 121212
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
