cursor #c0c6d5
cursor_text_color #2a313c

foreground            #929092
background            #131315
selection_foreground  #e0e2ec
selection_background  #43474e
url_color             #c0c6d5

# color0
# color1
# color2
# color3
# color4
# color5
# color6
# color7
#
# color8
# color9
# color10
# color11
# color12
# color13
# color14
# color15

# ANSI Colors (0-7) с фактором 0.65
#282828
color0 #282828
color1 #cc1065
color2 #68a149
color3 #db9724
color4 #4e8299
color5 #9869ac
color6 #459e99
color7 #969ba7

color8 #ffffff
color9 #ffffff
color10 #ffffff
color11 #ffffff
color12 #ffffff
color13 #ffffff
color14 #ffffff
color15 #ffffff

color #8888de
color0 #4e4e4e
color1 #ad95f7
color2 #7fb7da
color3 #b9d3f4
color4 #98a4b0
color5 #adb0ca
color6 #a0b9ca
color7 #c5c5c5

color8 #aeaeaf
color9 #d0befd
color10 #aedcfd
color11 #f2f7ff
color12 #bfc7d1
color13 #cacde8
color14 #b9daf1
color15 #ffffff
