cursor #debfc2
cursor_text_color #3f2b2e

foreground            #958f8f
background            #161313
selection_foreground  #f3dddf
selection_background  #524345
url_color             #debfc2

# color0
# color1
# color2
# color3
# color4
# color5
# color6
# color7
#
# color8
# color9
# color10
# color11
# color12
# color13
# color14
# color15

# ANSI Colors (0-7) с фактором 0.65
#b8cacd
color0 #2a2828
color1 #cd202b
color2 #c28700
color3 #ec8e3f
color4 #54809e
color5 #b4617d
color6 #9f913e
color7 #b09590

color8 #ffffff
color9 #ffffff
color10 #ffffff
color11 #ffffff
color12 #ffffff
color13 #ffffff
color14 #ffffff
color15 #ffffff

color #8888de
color0 #4f4f4f
color1 #d95b76
color2 #e3aea1
color3 #f5c6bf
color4 #b8a6a9
color5 #c3a1a9
color6 #d8b6b2
color7 #c8c8c8

color8 #b4aeae
color9 #fb929e
color10 #fed6ca
color11 #fff4f2
color12 #dac5c7
color13 #e7c1c7
color14 #fcd9d4
color15 #ffffff
