cursor #e6e1e9
cursor_text_color #cac4cf

foreground            #e6e1e9
background            #08080a
selection_foreground  #332e41
selection_background  #cbc3dc
url_color             #cebdfe

# black
color8   #3a383e
color0   #141318

# red
color9 #ffccd0
color1 #ffb2b9

# green
color10 #a7dcb6
color2 #95d5a7

# yellow
color11 #e3cd83
color3 #dec56e

# blue
# color4  #c6bfff
color12 #ddd9ff
color4  #cebdfe

# magenta
color13 #eccdf7
color5 #e4b7f3

# cyan
color14 #97dae7
color6 #82d3e2

# white
color7 #e6e1e9
color15 #cac4cf

