cursor #9acbfa
cursor_text_color #003352

foreground            #8c9198
background            #101418
selection_foreground  #d5e4f6
selection_background  #3a4857
url_color             #9acbfa

# ANSI Colors (0-7) с фактором 0.65
color0 #282828
color1 #a21be6
color2 #00a2ac
color3 #0cb3d8
color4 #50819b
color5 #7075bc
color6 #489caf
color7 #939ca6

# Bright Colors (8-15) с фактором 0.8
color8 #80868e
color9 #5484ff
color10 #00c3f8
color11 #86cfff
color12 #88a1b4
color13 #7f9dd2
color14 #6dbce3
color15 #cbdef1
