cursor #dee3e6
cursor_text_color #bfc8cc

foreground            #dee3e6
background            #050607
selection_foreground  #1e333b
selection_background  #b3cad4
url_color             #88d1ec

# black
color8   #353a3c
color0   #0f1416

# red
color9 #ffccd0
color1 #ffb2b9

# green
color10 #a7dcb6
color2 #95d5a7

# yellow
color11 #c3d696
color3 #b8cf84

# blue
# color4  #afc6ff
color12 #c8d8ff
color4  #88d1ec

# magenta
color13 #eccdf7
color5 #e4b7f3

# cyan
color14 #97dae6
color6 #82d3e1

# white
color7 #dee3e6
color15 #bfc8cc

