cursor #dee4e0
cursor_text_color #bec9c5

foreground            #dee4e0
background            #040605
selection_foreground  #1d352f
selection_background  #b1ccc4
url_color             #84d6c2

# black
color8   #343b38
color0   #0e1513

# red
color9 #ffc7af
color1 #ffb595

# green
color10 #a7dcb6
color2 #95d5a7

# yellow
color11 #c3d696
color3 #b8cf84

# blue
# color4  #afc6ff
color12 #c8d8ff
color4  #84d6c2

# magenta
color13 #eccdf7
color5 #e4b7f3

# cyan
color14 #94dbd3
color6 #81d5cb

# white
color7 #dee4e0
color15 #bec9c5

