cursor #e5e1e9
cursor_text_color #c8c5d0

foreground            #e5e1e9
background            #08080a
selection_foreground  #302e42
selection_background  #c7c4dc
url_color             #c4c0ff

# black
color8   #3a383f
color0   #131318

# red
color9 #ffccd0
color1 #ffb2b9

# green
color10 #a7dcb6
color2 #95d5a7

# yellow
color11 #c3d696
color3 #b8cf84

# blue
# color4  #c1c1ff
color12 #dbdbff
color4  #c4c0ff

# magenta
color13 #eccdf7
color5 #e4b7f3

# cyan
color14 #97dae7
color6 #82d3e2

# white
color7 #e5e1e9
color15 #c8c5d0

