cursor #F1DEDD
cursor_text_color #c1c7ce

active_border_color #FF8678
innactive_border_color #534342

foreground            #F1DEDD
background            #101417
selection_foreground  #21323e
selection_background  #b6c9d8
url_color             #92cef5
Add commentMore actions
# black
color0   #101417
color8   #41484d

# red
color1   #ff8678
color9   #ffb4ab

# green
color2   #D8AC63
color10   #ccc1e9

# yellow
color3   #FFABA4
color11   #c6e7ff

# blue
color4   #ff8678
color12   #ffb4ab

# magenta
color5   #D8AC63
color13   #ccc1e9

# cyan
color6   #FFABA4
color14   #c6e7ff

# white
color7   #D8C2C0
color15   #F1DEDD
