[main]
include = "~/.config/fuzzel/colors.ini"

font=JetBrains Mono NF:size=17
terminal=foot -e
prompt="> "
layer=overlay
lines=7
width=30
dpi-aware=no
inner-pad=20
horizontal-pad=40
vertical-pad=30
match-counter=no
image-size-ratio=0.5
line-height=45


# [colors]
# background=1f1f28ee  # sumiInk3
# text=dcd7badd        # lotusGray
# prompt=e6c384ff      # carpYellow
# placeholder=727169ff # fujiGray
# input=dcd7baff       # lotusGray
# match=ffa066ff       # indexed orange
# selection=c0a36e77   # boatYellow2
# selection-text=1f1f28ff  # sumiInk3 (тёмный — контраст на жёлтом)
# selection-match=e82424ff # lotusRed3
# counter=727169ff     # fujiGray
# border=c0a36e77      # boatYellow2

[border]
radius=20
width=2
selection-radius=10
