wallpaper {
    monitor = #eDP-1
    # path = ~/Pictures/Wallpapers/1-ambxst-blobs-red.png
    # path = /home/pundemia/Pictures/Wallpapers/wallhaven-polpoe.jpg
    # path = /home/pundemia/Pictures/Wallpapers/linux-15.png
    # path = /home/pundemia/Pictures/Wallpapers/blue-girl-window-sad.jpg
    # path = /home/pundemia/Pictures/Wallpapers/a_cartoon_of_a_girl_sitting_in_a_rocking_chair.png
    # path = ~/.local/state/caelestia/wallpaper/current
    path = ~/Pictures/Wallpapers/abstract-38.png
    fit_mode = cover
}
