source = ~/.config/hypr/modules/monitors.conf
source = ~/.config/hypr/modules/notebook.conf
source = ~/.config/hypr/modules/autostart.conf
source = ~/.config/hypr/modules/env.conf
source = ~/.config/hypr/modules/general.conf
source = ~/.config/hypr/modules/input.conf
source = ~/.config/hypr/modules/binds.conf
source = ~/.config/hypr/modules/rules.conf

# source = ~/.config/hypr/plugins/dynamic_cursor.conf
# source = ~/.config/hypr/plugins/hyprexpo.conf

# Ax-Shell
# source = ~/.config/Ax-Shell/config/hypr/ax-shell.conf

# pShell
source = ~/.config/quickshell/pShell/config/hypr/hyprland.conf
source = ~/.config/quickshell/testShell/config/hypr/hyprland.conf
# source = ~/.config/hypr/modules/grid_workspaces/grid_workspaces.conf
