#################
### AUTOSTART ###
#################

exec-once = /lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = urusai
exec = pgrep -x "hypridle" > /dev/null || uwsm app -- hypridle
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = hyprpm reload -n
exec-once = hyprshade on vibrance

