#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, s    tatus bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar #& 
# exec-once = hyprpaper
exec-once = /lib/polkit-gnome/polkit-gnome-authentication-agen    t-1
# exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"   # for GTK4 apps
# exec-once = wl-paste --type text --watch cliphist store
# exec-once = wl-paste --type image --watch cliphist store
exec-once = hyprctl setcursor Bibata-Modern-Classic 24

#fabric
# exec = swww init
#exec-once = cd ~/.config/fabric; python main.py
#exec = ln -sf $wallpaper ~/.current.wall
