$wallpaper = /home/pundemia/Pictures/Wallpapers/macos-big-sur.jpg
$background = 1a1111
$foreground = f0dede
$color0 = 413737
$color1 = ff7377
$color2 = ff8083
$color3 = ff8d90
$color4 = ff9a9c
$color5 = ffa6a9
$color6 = ffb3b5
$color7 = d7c1c1
$color8 = 524343
$color9 = ff9a9a
$color10 = ffa7a7
$color11 = ffb4b4
$color12 = ffc1c1
$color13 = ffcdcd
$color14 = ffdada
$color15 = f0dede

$primary = ffb3b5
$secondary = e6bdbd
$tertiary = e6c08d
$surface = 1a1111
$surface_bright = 413737
$error = ff5945
