#############
### INPUT ###
#############

# https://wiki.hyprland.org/Configuring/Variables/#input
input {
    kb_layout = us, ru
    kb_variant =
    kb_model =
    # kb_options = caps:ctrl_modifier#grp:caps_toggle#win_space_toggle #, ctrl:swap_lalt_lctl
    kb_options = grp:caps_toggle#win_space_toggle #, ctrl:swap_lalt_lctl
    # kb_options = grp:win_space_toggle #, ctrl:swap_lalt_lctl
    kb_rules =
    follow_mouse = 1
    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
    touchpad {
        natural_scroll = true
    }
}
# bind = , Caps_Lock, exec, hyprctl switchxkblayout current next
# bind = , ISO_Next_Group, exec, notify-send "Язык изменен"
# 2. Shift + Caps -> Настоящий Caps Lock
# Здесь wtype сработает, потому что мы не убили символ Caps Lock совсем
# bindn = SHIFT, code:66, exec, notify-send "ghbddjndkfn"
# bindn = SHIFT, code:66, exec, notify-send "ghbddjndkfn"
# https://wiki.hyprland.org/Configuring/Variables/#gestures
# gestures {
#     workspace_swipe = true
# }
gesture = 3, vertical, workspace
gesture = 3, horizontal, special, magic
gesture = 4, pinch, resize
#gesture = 4, pinchout, fullscreen, maximize
gesture = 4, swipe, move

# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#per-devi    ce-input-configs for more
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}
