##############################
### WINDOWS AND WORKSPACES ###
##############################
# windowrule = suppressevent maximize, class:.*
# Fix some dragging issues with XWayland
# windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# Kitty
windowrule = pseudo on, match:class kitty
windowrule = size (monitor_w*0.5) (monitor_h*0.5), match:class kitty

# Telegram
windowrule = workspace special:magic,match:class org.telegram.desktop
# windowrule = pseudo,class:^(org.telegram.desktop)$
windowrule = float on,match:class org.telegram.desktop
windowrule = move 1501 167,match:class org.telegram.desktop
windowrule = size 400 750,match:class org.telegram.desktop

# File-chooser
windowrule = float on, match:initial_title (File Upload|Choose Files|Save Image|Save File)
windowrule = size 600 350, match:initial_title (File Upload|Choose Files|Save Image|Save File)
windowrule = move (cursor_x-(window_w*0.5)) (cursor_y-(window_h*0.5)),match:initial_title (File Upload|Choose Files|Save Image|Save File)

# File-manager
windowrule = pseudo on, match:class org.gnome.Nautilus
windowrule = size 930 530, match:class org.gnome.Nautilus

# Firefox
#windowrule = workspace special:magic,match:initial_title (Mozilla Firefox)
#windowrule = float on,match:initial_title (Mozilla Firefox)
#windowrule = move 46 46,initialTitle:^(Mozilla Firefox)$
#windowrule = size 1400 1028,initialTitle:^(Mozilla Firefox)$

# Firefox picture-in-picture
windowrule = float on,match:initial_title (Picture-in-Picture)
windowrule = pin on,match:initial_title (Picture-in-Picture)
windowrule = opacity 1.0 override,match:initial_title (Picture-in-Picture)
windowrule = no_blur on,match:initial_title (Picture-in-Picture)

# Calc
windowrule = float on, match:class org.gnome.Calculator
windowrule = size 390 616,match:class org.gnome.Calculator
windowrule = move (cursor_x-(window_w*0.5)) (cursor_y-(window_h*0.5)),match:class org.gnome.Calculator

# freerdp
windowrule = tile on, match:class xfreerdp

# Gapless
windowrule = float on,match:initial_title Gapless
windowrule = size 720 580, match:initial_title Gapless
windowrule = workspace special:magic, match:initial_title Gapless

# VPN
#windowrule = float, class:AmneziaVPN
#windowrule = size 360 640, class:AmneziaVPN
#windowrule = move onscreen cursor -50% -50%,class:AmneziaVPN

# Fusion
#windowrule = opacity 0.4, initialTitle:Fusion360
#windowrule = noblur, initialTitle:Fusion360
# windowrule = stayfocused, initialTitle:Fusion360
# windowrule = noanim, initialTitle:Fusion360
# windowrule = nodim, initialTitle:Fusion360
# windowrule = noshadow, initialTitle:Fusion360
# windowrule = forcergbx, initialTitle:Fusion360

#windowrule = workspace special:magic,initialTitle:^(Морской бой)$
#windowrule = pseudo,initialTitle:^(Морской бой)$
#windowrule = size 603 910,initialTitle:^(Морской бой)$

#windowrule = workspace special:magic,initialTitle:^(Морской бой: уведомление)$
#windowrule = float,initialTitle:^(Морской бой: уведомление)$

#windowrule = workspace special:magic,initialTitle:^(Морской бой: настройки)$
#windowrule = float,initialTitle:^(Морской бой: настройки)$
#windowrule = workspace special:magic,initialTitle:^(Морской бой: инструкция)$
#windowrule = float,initialTitle:^(Морской бой: инструкция)$
#windowrule = size 200 100,initialTitle:^(Морской бой: уведомление)$

#
# Fabric
#layerrule = noanim, fabric
# layerrule = ignorealpha 0.75, fabric
# blurls=fabric
