##############################
### WINDOWS AND WORKSPACES ###
##############################
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for     more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ f    or workspace rules
# Ignore maximize requests from apps. You'll probably like thi    s.
windowrule = suppressevent maximize, class:.*
# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# Kitty
windowrule = pseudo,class:^(kitty)$,title:^(kitty)$
windowrule = size 930 530,class:^(kitty)$,title:^(kitty)$

# Telegram
windowrule = workspace special:magic,class:^(org.telegram.desktop)$
# windowrule = pseudo,class:^(org.telegram.desktop)$
windowrule = float,class:^(org.telegram.desktop)$
windowrule = move 1501 167,class:^(org.telegram.desktop)$
windowrule = size 400 750,class:^(org.telegram.desktop)$

# File-chooser
windowrule = float, initialTitle:^(File Upload|Choose Files|Save Image|Save File)$
windowrule = size 600 350, initialTitle:^(File Upload|Choose Files|Save Image|Save File)$
windowrule = move onscreen cursor -50% -50%,initialTitle:^(File Upload|Choose Files|Save Image|Save File)$

# File-manager
windowrule = pseudo, class:org.gnome.Nautilus
windowrule = size 930 530, class:org.gnome.Nautilus

# Firefox
windowrule = workspace special:magic,initialTitle:^(Mozilla Firefox)$
windowrule = float,initialTitle:^(Mozilla Firefox)$
windowrule = move 46 46,initialTitle:^(Mozilla Firefox)$
windowrule = size 1400 1028,initialTitle:^(Mozilla Firefox)$

# Firefox picture-in-picture
windowrule = workspace 1,initialTitle:^(Picture-in-Picture)$
windowrule = float,initialTitle:^(Picture-in-Picture)$
windowrule = pin,initialTitle:^(Picture-in-Picture)$

# Calc
windowrule = float, class:org.gnome.Calculator
windowrule = size 390 616, class:org.gnome.Calculator
windowrule = move onscreen cursor -50% -50%,class:org.gnome.Calculator

# Gapless
windowrule = float, initialTitle:Gapless
windowrule = size 720 580, initialTitle:Gapless
windowrule = workspace special:magic, initialTitle:Gapless

# VPN
windowrule = float, class:AmneziaVPN
windowrule = size 360 640, class:AmneziaVPN
windowrule = move onscreen cursor -50% -50%,class:AmneziaVPN

# Fusion
windowrule = opacity 0.4, initialTitle:Fusion360 
windowrule = noblur, initialTitle:Fusion360 
# windowrule = stayfocused, initialTitle:Fusion360 
# windowrule = noanim, initialTitle:Fusion360 
# windowrule = nodim, initialTitle:Fusion360 
# windowrule = noshadow, initialTitle:Fusion360 
# windowrule = forcergbx, initialTitle:Fusion360 

# windowrule = workspace special:magic,initialTitle:^(Морской бой)$
# windowrule = pseudo,initialTitle:^(Морской бой)$
# windowrule = size 603 910,initialTitle:^(Морской бой)$
#
# windowrule = workspace special:magic,initialTitle:^(Морской бой: уведомление)$
# windowrule = float,initialTitle:^(Морской бой: уведомление)$
#
# windowrule = workspace special:magic,initialTitle:^(Морской бой: настройки)$
# windowrule = float,initialTitle:^(Морской бой: настройки)$
# windowrule = workspace special:magic,initialTitle:^(Морской бой: инструкция)$
# windowrule = float,initialTitle:^(Морской бой: инструкция)$
# windowrule = size 603 910,initialTitle:^(Морской бой: уведомление)$

# 
# Fabric
layerrule = noanim, fabric
# layerrule = ignorealpha 0.75, fabric
# blurls=fabric
