[General]
contrastUiColor={{colors.primary.default.hex}}
drawColor={{colors.primary.default.hex}}
uiColor={{colors.surface_bright.default.hex}}
userColors={{colors.red.default.hex}}, {{colors.green.default.hex}}, {{colors.yellow.default.hex}}, {{colors.blue.default.hex}}, {{colors.magenta.default.hex}}, {{colors.cyan.default.hex}}, {{colors.white.default.hex}}
