:root {
    --bg: {{colors.surface_container_lowest.default.hex}};
    --surface: {{colors.surface_container_low.default.hex}};
    --surface-low: {{colors.surface_container.default.hex}};
    --surface-high: {{colors.surface_container_high.default.hex}};
    --primary: {{colors.primary.default.hex}};
    --on-surface: {{colors.on_surface.default.hex}};
    --on-surface-variant: {{colors.on_surface_variant.default.hex}};
}
