/* waybar — color palette */
/* edit this file to retheme everything */

@define-color bg            {{colors.surface.default.hex}};
@define-color surface       {{colors.surface_container.default.hex}};   /* подложки групп/трея/воркспейсов (добавь альфу при желании) */
@define-color surface_solid {{colors.surface_container.default.hex}};
@define-color hover         {{colors.surface_container.default.hex}};

@define-color color1        {{colors.tertiary.default.hex}};    /* арч, инструменты, часы               */
@define-color color2        {{colors.secondary.default.hex}};    /* батарея, вайфай, блютуз, раскладка,  */
                                       /* кнопка выкл, подложка активного ws   */
@define-color color2_dim    {{colors.primary.default.hex}};    /* подложка активного воркспейса        */
@define-color color2_err    {{colors.error.default.hex}};    /* низкий заряд / ошибка               */

@define-color ws_inactive   {{colors.outline_variant.default.hex}};    /* текст неактивного воркспейса         */
@define-color ws_active     {{colors.on_primary.default.hex}};    /* текст активного воркспейса           */

