$wallpaper = /home/pundemia/Pictures/Wallpapers/aesthetic-forest.png
$background = 0f1417
$foreground = dfe3e7
$color0 = 353a3d
$color1 = 54b7e9
$color2 = 5fbcea
$color3 = 6ac1ec
$color4 = 75c6ed
$color5 = 81caef
$color6 = 8ccff0
$color7 = c0c8cd
$color8 = 40484c
$color9 = 7fd3ff
$color10 = 8cd7ff
$color11 = 99dcff
$color12 = a6e0ff
$color13 = b2e5ff
$color14 = bfe9ff
$color15 = dfe3e7

$primary = 8ccff0
$secondary = b4cad6
$tertiary = c7c2ea
$surface = 0f1417
$surface_bright = 353a3d
$error = ff5945
