animations {
    enabled = yes
    bezier = myBezier, 0.4, 0.0, 0.2, 1.0
    animation = workspaces, 1, 2.5, myBezier, slidefadevert 20%
}

bind = SUPER CTRL, left, exec, ~/.config/hypr/modules/grid_workspaces/left.sh
bind = SUPER CTRL, right, exec, ~/.config/hypr/modules/grid_workspaces/right.sh 
bind = SUPER CTRL, up, exec, ~/.config/hypr/modules/grid_workspaces/up.sh
bind = SUPER CTRL, down, exec, ~/.config/hypr/modules/grid_workspaces/down.sh 

